### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by valepe** [voidtrance/voron-klipper-extensions#7] opened 2023-09-30 16:05 UTC
How can I uninstall it?

**Comment by zapl** [comment] 2023-10-01 23:26
edit `/etc/rc.local` (e.g. `sudo nano /etc/rc.local`) and remove the line that says
```
cd /home/pi/eis && nohup ./eis &
```
once you reboot it won't start again, and if you like you can now remove the eis folder (e.g. `rm -rf ~/eis`)

**Comment by voidtrance** [comment] 2023-10-11 17:57
Closing this as this is not a bug but rather a feature request. I can work on adding an uninstall option.

For now, you can run the following commands:
```shell
rm -f ~/klipper/klippy/extras/gcode_shell_command.py ~/klipper/klippy/extras/settling_probe.py ~/klipper/klippy/extras/led_interpolate.py ~/klipper/klippy/extras/state_notify.py
sudo service klipper restart
```

**Closed by voidtrance** 2023-10-11 17:57 UTC
